# -*- coding: utf-8 -*-
"""
Spyder Editor

This is a temporary script file.
"""
import matplotlib
from PIL import ImageGrab
from PIL import Image
import time
import pyautogui as p
import random
i=0
#for x in range (4):
   # print('test')
   # time.sleep(12)
   # i+=1
   # print(p.displayMousePosition())




#pyautogui.typewrite('Hello world!\n', interval=secs_between_keys)  # useful for entering text, newline is Enter
list = [ "Niner nation", "Lol smiley face", "lets goo delta sigs", "WE gotta win this ish", "Red cups are the best", "im getting tired",
         "my fingers hurt", "My eyes are tired", "Pizzaaaa", "hot dogs", "burgers", "ramen", "FIve Guys", "I love food", "go chiefs", "super bowl 55 is coming", "jamis is lame", 
         "I love haven”, “haven4","haven haven", "I love my cat", "I kind of like dogs","“Kellan is the GOAT", 
         "Gabubu", "Dub season boys!", "Yes sir", "Pizza time", "America", "Ok", "Dsig", "Love it boys" ,"Get it", 
         "Lol", "Best there ever was", "Love life gentlemen", "pizza time", "Lets win it", "pizzzzzzaaaaa time",
        "Summer time tho", "Team Joe exotic", "Love life", "Lets win this", "Goodluck lol", "big win”, “oh yes",
        "Yesssssss", "sirrrr",
        "Keep", "pounding",
        "I", "like", "oranges", "Word", "I miss ricky", "Lets get these chips", 
        "Cuppa army", "Cuppa army 2.0", "Lets goo", "we got this", "Lets go.",
        "YITBOS.", "Let’s get this bread.", "Moody the goat.", "I love delta sig.", 
        "Delta sig for life.", "We got this.", "We are trying to win.", "We gotta win!.,"
        "Bread time.", "Pizza time.", "Pool time.", "Showfety’s coins.", "Lets win this ish.", 
        "Dub seasonnnn.", "Woot Woot.", "I love marvel.", "Im a niner.", "Niner nation.", "Lol smiley face.", 
        "lets goo delta sigs.", "WE gotta win this ish.", "Red cups are the best.", "im getting tired.",
        "oh yes.","YITBOS", "EZ DUB", "=)", "EZ 500", "RIP KOBE","Yesssssss", "sirrrr", "help" ,
        "Lets go", "Let’s get this bread", 
         "I love delta sig", "Delta sig for life", "We got this", "We are trying to win", "We gotta win!", "Bread time", "Pizza time", "Pool time", "Showfety’s coins", "Lets win this ish",
         "Dub seasonnnn", "Woot Woot", "I love marvel", "Im a niner", "Niner nation", "Lol smiley face", "lets goo delta sigs", "WE gotta win this ish", "Red cups are the best", "im getting tired",
         "my fingers hurt", "My eyes are tired", "Pizzaaaa", "hot dogs", "burgers", "ramen", "FIve Guys", "I love food", "go chiefs", "super bowl 55 is coming", "jamis is lame", 
         "I love haven”, “haven4","haven haven", "I love my cat", "I kind of like dogs","“Kellan is the GOAT", 
         "Gabubu", "Dub season boys!", "Yes sir", "Pizza time", "America", "Ok", "Dsig", "Love it boys" ,"Get it", 
         "Lol", "Best there ever was", "Love life gentlemen", "pizza time", "Lets win it", "pizzzzzzaaaaa time",
        "Summer time tho", "Team Joe exotic", "Love life", "Lets win this", "Goodluck lol", "big win”, “oh yes",
        "Yesssssss", "sirrrr",
        "Keep", "pounding",
        "I", "like", "oranges", "Word", "I miss ricky", "Lets get these chips", 
        "Cuppa army", "Cuppa army 2.0", "Lets goo", "we got this", "Lets go.",
        "YITBOS.", "Let’s get this bread.", "Moody the goat.", "I love delta sig.", 
        "Delta sig for life.", "We got this.", "We are trying to win.", "We gotta win!.,"
        "Bread time.", "Pizza time.", "Pool time.", "Showfety’s coins.", "Lets win this ish.", 
        "Dub seasonnnn.", "Woot Woot.", "I love marvel.", "Im a niner.", "Niner nation.", "Lol smiley face.", 
        "lets goo delta sigs.", "WE gotta win this ish.", "Red cups are the best.", "im getting tired.",
        "oh yes.","YITBOS", "EZ DUB", "=)", "EZ 500", "RIP KOBE","Yesssssss", "sirrrr", "help" ,
        "Lets go", "Let’s get this bread", 
         "I love delta sig", "Delta sig for life", "We got this", "We are trying to win", "We gotta win!", "Bread time", "Pizza time", "Pool time", "Showfety’s coins", "Lets win this ish",
         "Dub seasonnnn", "Woot Woot", "I love marvel", "Im a niner", "Niner nation", "Lol smiley face", "lets goo delta sigs", "WE gotta win this ish", "Red cups are the best", "im getting tired",
         "my fingers hurt", "My eyes are tired", "Pizzaaaa", "hot dogs", "burgers", "ramen", "FIve Guys", "I love food", "go chiefs", "super bowl 55 is coming", "jamis is lame", 
         "I love haven”, “haven4","haven haven", "I love my cat", "I kind of like dogs","“Kellan is the GOAT", 
         "Gabubu", "Dub season boys!", "Yes sir", "Pizza time", "America", "Ok", "Dsig", "Love it boys" ,"Get it", 
         "Lol", "Best there ever was", "Love life gentlemen", "pizza time", "Lets win it", "pizzzzzzaaaaa time",
        "Summer time tho", "Team Joe exotic", "Love life", "Lets win this", "Goodluck lol", "big win”, “oh yes",
        "Yesssssss", "sirrrr",
        "Keep", "pounding",
        "I", "like", "oranges", "Word", "I miss ricky", "Lets get these chips", 
        "Cuppa army", "Cuppa army 2.0", "Lets goo", "we got this", "Lets go.",
        "YITBOS.", "Let’s get this bread.", "Moody the goat.", "I love delta sig.", 
        "Delta sig for life.", "We got this.", "We are trying to win.", "We gotta win!.,"
        "Bread time.", "Pizza time.", "Pool time.", "Showfety’s coins.", "Lets win this ish.", 
        "Dub seasonnnn.", "Woot Woot.", "I love marvel.", "Im a niner.", "Niner nation.", "Lol smiley face.", 
        "lets goo delta sigs.", "WE gotta win this ish.", "Red cups are the best.", "im getting tired.",
        "oh yes.","YITBOS", "EZ DUB", "=)", "EZ 500", "RIP KOBE","Yesssssss", "sirrrr", "help" ,
        "Lets go", "Let’s get this bread", 
         "I love delta sig", "Delta sig for life", "We got this", "We are trying to win", "We gotta win!", "Bread time", "Pizza time", "Pool time", "Showfety’s coins", "Lets win this ish",
         "Dub seasonnnn", "Woot Woot", "I love marvel", "Im a niner", "Niner nation", "Lol smiley face", "lets goo delta sigs", "WE gotta win this ish", "Red cups are the best", "im getting tired",
         "my fingers hurt", "My eyes are tired", "Pizzaaaa", "hot dogs", "burgers", "ramen", "FIve Guys", "I love food", "go chiefs", "super bowl 55 is coming", "jamis is lame", 
         "I love haven”, “haven4","haven haven", "I love my cat", "I kind of like dogs","“Kellan is the GOAT", 
         "Gabubu", "Dub season boys!", "Yes sir", "Pizza time", "America", "Ok", "Dsig", "Love it boys" ,"Get it", 
         "Lol", "Best there ever was", "Love life gentlemen", "pizza time", "Lets win it", "pizzzzzzaaaaa time",
        "Summer time tho", "Team Joe exotic", "Love life", "Lets win this", "Goodluck lol", "big win”, “oh yes",
        "Yesssssss", "sirrrr",
        "Keep", "pounding",
        "I", "like", "oranges", "Word", "I miss ricky", "Lets get these chips", 
        "Cuppa army", "Cuppa army 2.0", "Lets goo", "we got this", "Lets go.",
        "YITBOS.", "Let’s get this bread.", "Moody the goat.", "I love delta sig.", 
        "Delta sig for life.", "We got this.", "We are trying to win.", "We gotta win!.,"
        "Bread time.", "Pizza time.", "Pool time.", "Showfety’s coins.", "Lets win this ish.", 
        "Dub seasonnnn.", "Woot Woot.", "I love marvel.", "Im a niner.", "Niner nation.", "Lol smiley face.", 
        "lets goo delta sigs.", "WE gotta win this ish.", "Red cups are the best.", "im getting tired.",
        "oh yes.","YITBOS", "EZ DUB", "=)", "EZ 500", "RIP KOBE","Yesssssss", "sirrrr", "help" ,
        "Lets go", "Let’s get this bread", 
         "I love delta sig", "Delta sig for life", "We got this", "We are trying to win", "We gotta win!", "Bread time", "Pizza time", "Pool time", "Showfety’s coins", "Lets win this ish",
         "Dub seasonnnn", "Woot Woot", "I love marvel", "Im a niner", "Niner nation", "Lol smiley face", "lets goo delta sigs", "WE gotta win this ish", "Red cups are the best", "im getting tired",
         "my fingers hurt", "My eyes are tired", "Pizzaaaa", "hot dogs", "burgers", "ramen", "FIve Guys", "I love food", "go chiefs", "super bowl 55 is coming", "jamis is lame", 
         "I love haven”, “haven4","haven haven", "I love my cat", "I kind of like dogs","“Kellan is the GOAT", 
         "Gabubu", "Dub season boys!", "Yes sir", "Pizza time", "America", "Ok", "Dsig", "Love it boys" ,"Get it", 
         "Lol", "Best there ever was", "Love life gentlemen", "pizza time", "Lets win it", "pizzzzzzaaaaa time",
        "Summer time tho", "Team Joe exotic", "Love life", "Lets win this", "Goodluck lol", "big win”, “oh yes",
        "Yesssssss", "sirrrr",
        "Keep", "pounding",
        "I", "like", "oranges", "Word", "I miss ricky", "Lets get these chips", 
        "Cuppa army", "Cuppa army 2.0", "Lets goo", "we got this", "Lets go.",
        "YITBOS.", "Let’s get this bread.", "Moody the goat.", "I love delta sig.", 
        "Delta sig for life.", "We got this.", "We are trying to win.", "We gotta win!.,"
        "Bread time.", "Pizza time.", "Pool time.", "Showfety’s coins.", "Lets win this ish.", 
        "Dub seasonnnn.", "Woot Woot.", "I love marvel.", "Im a niner.", "Niner nation.", "Lol smiley face.", 
        "lets goo delta sigs.", "WE gotta win this ish.", "Red cups are the best.", "im getting tired.",
        "oh yes.","YITBOS", "EZ DUB", "=)", "EZ 500", "RIP KOBE","Yesssssss", "sirrrr", "help" ,
        "Lets go", "Let’s get this bread", 
         "I love delta sig", "Delta sig for life", "We got this", "We are trying to win", "We gotta win!", "Bread time", "Pizza time", "Pool time", "Showfety’s coins", "Lets win this ish",
         "Dub seasonnnn", "Woot Woot", "I love marvel", "Im a niner", "Niner nation", "Lol smiley face", "lets goo delta sigs", "WE gotta win this ish", "Red cups are the best", "im getting tired",
         "my fingers hurt", "My eyes are tired", "Pizzaaaa", "hot dogs", "burgers", "ramen", "FIve Guys", "I love food", "go chiefs", "super bowl 55 is coming", "jamis is lame", 
         "I love haven”, “haven4","haven haven", "I love my cat", "I kind of like dogs","“Kellan is the GOAT", 
         "Gabubu", "Dub season boys!", "Yes sir", "Pizza time", "America", "Ok", "Dsig", "Love it boys" ,"Get it", 
         "Lol", "Best there ever was", "Love life gentlemen", "pizza time", "Lets win it", "pizzzzzzaaaaa time",
        "Summer time tho", "Team Joe exotic", "Love life", "Lets win this", "Goodluck lol", "big win”, “oh yes",
        "Yesssssss", "sirrrr",
        "Keep", "pounding",
        "I", "like", "oranges", "Word", "I miss ricky", "Lets get these chips", 
        "Cuppa army", "Cuppa army 2.0", "Lets goo", "we got this", "Lets go.",
        "YITBOS.", "Let’s get this bread.", "Moody the goat.", "I love delta sig.", 
        "Delta sig for life.", "We got this.", "We are trying to win.", "We gotta win!.,"
        "Bread time.", "Pizza time.", "Pool time.", "Showfety’s coins.", "Lets win this ish.", 
        "Dub seasonnnn.", "Woot Woot.", "I love marvel.", "Im a niner.", "Niner nation.", "Lol smiley face.", 
        "lets goo delta sigs.", "WE gotta win this ish.", "Red cups are the best.", "im getting tired.",
        "oh yes.","YITBOS", "EZ DUB", "=)", "EZ 500", "RIP KOBE","Yesssssss", "sirrrr", "help" ,
        "Lets go", "Let’s get this bread", 
         "I love delta sig", "Delta sig for life", "We got this", "We are trying to win", "We gotta win!", "Bread time", "Pizza time", "Pool time", "Showfety’s coins", "Lets win this ish",
         "Dub seasonnnn", "Woot Woot", "I love marvel", "Im a niner", "Niner nation", "Lol smiley face", "lets goo delta sigs", "WE gotta win this ish", "Red cups are the best", "im getting tired",
         "my fingers hurt", "My eyes are tired", "Pizzaaaa", "hot dogs", "burgers", "ramen", "FIve Guys", "I love food", "go chiefs", "super bowl 55 is coming", "jamis is lame", 
         "I love haven”, “haven4","haven haven", "I love my cat", "I kind of like dogs","“Kellan is the GOAT", 
         "Gabubu", "Dub season boys!", "Yes sir", "Pizza time", "America", "Ok", "Dsig", "Love it boys" ,"Get it", 
         "Lol", "Best there ever was", "Love life gentlemen", "pizza time", "Lets win it", "pizzzzzzaaaaa time",
        "Summer time tho", "Team Joe exotic", "Love life", "Lets win this", "Goodluck lol", "big win”, “oh yes",
        "Yesssssss", "sirrrr",
        "Keep", "pounding",
        "I", "like", "oranges", "Word", "I miss ricky", "Lets get these chips", 
        "Cuppa army", "Cuppa army 2.0", "Lets goo", "we got this", "Lets go.",
        "YITBOS.", "Let’s get this bread.", "Moody the goat.", "I love delta sig.", 
        "Delta sig for life.", "We got this.", "We are trying to win.", "We gotta win!.,"
        "Bread time.", "Pizza time.", "Pool time.", "Showfety’s coins.", "Lets win this ish.", 
        "Dub seasonnnn.", "Woot Woot.", "I love marvel.", "Im a niner.", "Niner nation.", "Lol smiley face.", 
        "lets goo delta sigs.", "WE gotta win this ish.", "Red cups are the best.", "im getting tired.",
        "oh yes.","YITBOS", "EZ DUB", "=)", "EZ 500", "RIP KOBE","Yesssssss", "sirrrr", "help" ,
        "Lets go", "Let’s get this bread", 
         "I love delta sig", "Delta sig for life", "We got this", "We are trying to win", "We gotta win!", "Bread time", "Pizza time", "Pool time", "Showfety’s coins", "Lets win this ish",
         "Dub seasonnnn", "Woot Woot", "I love marvel", "Im a niner", "Niner nation", "Lol smiley face", "lets goo delta sigs", "WE gotta win this ish", "Red cups are the best", "im getting tired",
         "my fingers hurt", "My eyes are tired", "Pizzaaaa", "hot dogs", "burgers", "ramen", "FIve Guys", "I love food", "go chiefs", "super bowl 55 is coming", "jamis is lame", 
         "I love haven”, “haven4","haven haven", "I love my cat", "I kind of like dogs","“Kellan is the GOAT", 
         "Gabubu", "Dub season boys!", "Yes sir", "Pizza time", "America", "Ok", "Dsig", "Love it boys" ,"Get it", 
         "Lol", "Best there ever was", "Love life gentlemen", "pizza time", "Lets win it", "pizzzzzzaaaaa time",
        "Summer time tho", "Team Joe exotic", "Love life", "Lets win this", "Goodluck lol", "big win”, “oh yes",
        "Yesssssss", "sirrrr",
        "Keep", "pounding",
        "I", "like", "oranges", "Word", "I miss ricky", "Lets get these chips", 
        "Cuppa army", "Cuppa army 2.0", "Lets goo", "we got this", "Lets go.",
        "YITBOS.", "Let’s get this bread.", "Moody the goat.", "I love delta sig.", 
        "Delta sig for life.", "We got this.", "We are trying to win.", "We gotta win!.,"
        "Bread time.", "Pizza time.", "Pool time.", "Showfety’s coins.", "Lets win this ish.", 
        "Dub seasonnnn.", "Woot Woot.", "I love marvel.", "Im a niner.", "Niner nation.", "Lol smiley face.", 
        "lets goo delta sigs.", "WE gotta win this ish.", "Red cups are the best.", "im getting tired.",
        "oh yes.","YITBOS", "EZ DUB", "=)", "EZ 500", "RIP KOBE","Yesssssss", "sirrrr", "help" ,
        "Lets go", "Let’s get this bread", 
         "I love delta sig", "Delta sig for life", "We got this", "We are trying to win", "We gotta win!", "Bread time", "Pizza time", "Pool time", "Showfety’s coins", "Lets win this ish",
         "Dub seasonnnn", "Woot Woot", "I love marvel", "Im a niner", "Niner nation", "Lol smiley face", "lets goo delta sigs", "WE gotta win this ish", "Red cups are the best", "im getting tired",
         "my fingers hurt", "My eyes are tired", "Pizzaaaa", "hot dogs", "burgers", "ramen", "FIve Guys", "I love food", "go chiefs", "super bowl 55 is coming", "jamis is lame", 
         "I love haven”, “haven4","haven haven", "I love my cat", "I kind of like dogs","“Kellan is the GOAT", 
         "Gabubu", "Dub season boys!", "Yes sir", "Pizza time", "America", "Ok", "Dsig", "Love it boys" ,"Get it", 
         "Lol", "Best there ever was", "Love life gentlemen", "pizza time", "Lets win it", "pizzzzzzaaaaa time",
        "Summer time tho", "Team Joe exotic", "Love life", "Lets win this", "Goodluck lol", "big win”, “oh yes",
        "Yesssssss", "sirrrr",
        "Keep", "pounding",
        "I", "like", "oranges", "Word", "I miss ricky", "Lets get these chips", 
        "Cuppa army", "Cuppa army 2.0", "Lets goo", "we got this", "Lets go.",
        "YITBOS.", "Let’s get this bread.", "Moody the goat.", "I love delta sig.", 
        "Delta sig for life.", "ΔΣΦ", "We got this.", "We are trying to win.", "We gotta win!.,"
        "Bread time.", "Pizza time.", "Pool time.", "Showfety’s coins.", "Lets win this ish.", 
        "Dub seasonnnn.", "Woot Woot.", "I love marvel.", "Im a niner.", "Niner nation.", "Lol smiley face.", 
        "lets goo delta sigs.", "WE gotta win this ish.", "Red cups are the best.", "im getting tired.",
        "oh yes.","YITBOS", "EZ DUB", "=)", "EZ 500", "RIP KOBE","Yesssssss", "sirrrr", "help" ,
        "Lets go", "Let’s get this bread", 
         "I love delta sig", "Delta sig for life", "We got this", "We are trying to win", "We gotta win!", "Bread time", "Pizza time", "Pool time", "Showfety’s coins", "Lets win this ish",
         "Dub seasonnnn", "Woot Woot", "I love marvel", "Im a niner", "Niner nation", "Lol smiley face", "lets goo delta sigs", "WE gotta win this ish", "Red cups are the best", "im getting tired",
         "my fingers hurt", "My eyes are tired", "Pizzaaaa", "hot dogs", "burgers", "ramen", "FIve Guys", "I love food", "go chiefs", "super bowl 55 is coming", "jamis is lame", 
         "I love haven”, “haven4","haven haven", "I love my cat", "I kind of like dogs","“Kellan is the GOAT", 
         "Gabubu", "Dub season boys!", "Yes sir", "Pizza time", "America", "Ok", "Dsig", "Love it boys" ,"Get it", 
         "Lol", "Best there ever was", "Love life gentlemen", "pizza time", "Lets win it", "pizzzzzzaaaaa time",
        "Summer time tho", "Team Joe exotic", "Love life", "Lets win this", "Goodluck lol", "big win”, “oh yes",
        "Yesssssss", "sirrrr",
        "Keep", "pounding",
        "I", "like", "oranges", "ΔΣΦ", "Word", "I miss ricky", "Lets get these chips", 
        "Cuppa army", "Cuppa army 2.0", "Lets goo", "we got this", "Lets go.",
        "YITBOS.", "Let’s get this bread.", "Moody the goat.", "I love delta sig.", 
        "Delta sig for life.", "We got this.", "We are trying to win.", "We gotta win!.,"
        "Bread time.", "Pizza time.", "Pool time.", "Showfety’s coins.", "Lets win this ish.", 
        "Dub seasonnnn.", "Woot Woot.", "I love marvel.", "Im a niner.", "Niner nation.", "Lol smiley face.", 
        "lets goo delta sigs.", "WE gotta win this ish.", "Red cups are the best.", "im getting tired.",
        "oh yes.","YITBOS", "EZ DUB", "=)", "EZ 500", "RIP KOBE","Yesssssss", "sirrrr", "help" ,
        "Lets go", "Let’s get this bread", 
         "I love delta sig", "Delta sig for life", "We got this", "We are trying to win", "We gotta win!", "Bread time", "Pizza time", "Pool time", "Showfety’s coins", "Lets win this ish",
         "Dub seasonnnn", "Woot Woot", "I love marvel", "Im a niner", "Niner nation", "Lol smiley face", "lets goo delta sigs", "WE gotta win this ish", "Red cups are the best", "im getting tired",
         "my fingers hurt", "My eyes are tired", "Pizzaaaa", "hot dogs", "burgers", "ramen", "FIve Guys", "I love food", "go chiefs", "super bowl 55 is coming", "jamis is lame", 
         "I love haven”, “haven4","haven haven", "I love my cat", "I kind of like dogs","“Kellan is the GOAT", 
         "Gabubu", "Dub season boys!", "Yes sir", "Pizza time", "America", "Ok", "Dsig", "Love it boys" ,"Get it", 
         "Lol", "Best there ever was", "Love life gentlemen", "pizza time", "Lets win it", "pizzzzzzaaaaa time",
        "Summer time tho", "Team Joe exotic", "Love life", "Lets win this", "Goodluck lol", "big win”, “oh yes",
        "Yesssssss", "sirrrr",
        "Keep", "pounding",
        "I", "like", "oranges","ΔΣΦ",  "Word", "I miss ricky", "Lets get these chips", 
        "Cuppa army", "Cuppa army 2.0", "Lets goo", "we got this", "Lets go.",
        "YITBOS.", "Let’s get this bread.", "Moody the goat.", "I love delta sig.", 
        "Delta sig for life.", "We got this.", "We are trying to win.", "We gotta win!.,"
        "Bread time.", "Pizza time.", "Pool time.", "Showfety’s coins.", "Lets win this ish.", 
        "Dub seasonnnn.", "Woot Woot.", "I love marvel.", "Im a niner.", "Niner nation.", "Lol smiley face.", 
        "lets goo delta sigs.", "WE gotta win this ish.", "Red cups are the best.", "im getting tired.",
        "oh yes.","YITBOS", "EZ DUB", "=)", "EZ 500", "RIP KOBE","Yesssssss", "sirrrr", "help" ,
        "Lets go", "Let’s get this bread", 
         "I love delta sig", "ΔΣΦ", "Delta sig for life", "We got this", "We are trying to win", "We gotta win!", "Bread time", "Pizza time", "Pool time", "Showfety’s coins", "Lets win this ish",
         "Dub seasonnnn", "Woot Woot", "I love marvel", "Im a niner", "Niner nation", "Lol smiley face", "lets goo delta sigs", "WE gotta win this ish", "Red cups are the best", "im getting tired",
         "my fingers hurt", "My eyes are tired", "Pizzaaaa", "hot dogs", "burgers", "ramen", "FIve Guys", "I love food", "go chiefs", "super bowl 55 is coming", "jamis is lame", 
         "I love haven”, “haven4","haven haven", "I love my cat", "I kind of like dogs","“Kellan is the GOAT", 
         "Gabubu", "Dub season boys!", "Yes sir", "Pizza time", "America", "Ok", "Dsig", "Love it boys" ,"Get it", 
         "Lol", "Best there ever was", "Love life gentlemen", "pizza time", "Lets win it", "pizzzzzzaaaaa time",
        "Summer time tho", "Team Joe exotic", "Love life", "Lets win this", "Goodluck lol", "big win”, “oh yes",
        "Yesssssss", "sirrrr",
        "Keep", "pounding",
        "I", "like", "oranges","ΔΣΦ",  "Word", "I miss ricky", "Lets get these chips", 
        "Cuppa army", "Cuppa army 2.0", "Lets goo", "we got this", "Lets go.",
        "YITBOS.", "Let’s get this bread.", "Moody the goat.", "I love delta sig.", 
        "Delta sig for life.", "We got this.", "We are trying to win.", "We gotta win!.,"
        "Bread time.", "Pizza time.", "Pool time.", "Showfety’s coins.", "Lets win this ish.", 
        "Dub seasonnnn.", "Woot Woot.", "I love marvel.", "Im a niner.", "Niner nation.", "Lol smiley face.", 
        "lets goo delta sigs.", "WE gotta win this ish.", "Red cups are the best.", "im getting tired.",
        "oh yes.","YITBOS", "EZ DUB", "=)", "EZ 500", "RIP KOBE","Yesssssss", "sirrrr", "help" ,
        "Lets go", "Let’s get this bread", 
         "I love delta sig", "Delta sig for life", "We got this", "We are trying to win", "We gotta win!", "Bread time", "Pizza time", "Pool time", "Showfety’s coins", "Lets win this ish",
         "Dub seasonnnn", "Woot Woot", "I love marvel", "Im a niner", "Niner nation", "Lol smiley face", "lets goo delta sigs", "WE gotta win this ish", "Red cups are the best", "im getting tired",
         "my fingers hurt", "My eyes are tired", "Pizzaaaa", "hot dogs", "burgers", "ramen", "FIve Guys", "I love food", "go chiefs", "super bowl 55 is coming", "jamis is lame", 
         "I love haven”, “haven4","haven haven", "I love my cat", "I kind of like dogs","“Kellan is the GOAT", 
         "Gabubu", "Dub season boys!", "Yes sir", "Pizza time", "America", "Ok", "Dsig", "Love it boys" ,"Get it", 
         "Lol", "Best there ever was", "Love life gentlemen", "pizza time", "Lets win it", "pizzzzzzaaaaa time",
        "Summer time tho", "Team Joe exotic", "Love life", "Lets win this", "Goodluck lol", "big win”, “oh yes",
        "Yesssssss", "sirrrr",
        "Keep", "pounding",
        "I", "like", "oranges", "ΔΣΦ", "Word", "I miss ricky", "Lets get these chips", 
        "Cuppa army", "Cuppa army 2.0", "Lets goo", "we got this", "Lets go.",
        "YITBOS.", "Let’s get this bread.", "Moody the goat.", "I love delta sig.", 
        "Delta sig for life.", "We got this.", "We are trying to win.", "We gotta win!.,"
        "Bread time.", "Pizza time.", "Pool time.", "Showfety’s coins.", "Lets win this ish.", 
        "Dub seasonnnn.", "Woot Woot.", "I love marvel.", "Im a niner.", "Niner nation.", "Lol smiley face.", 
        "lets goo delta sigs.", "WE gotta win this ish.", "Red cups are the best.", "im getting tired.",
        "oh yes.","YITBOS", "EZ DUB", "=)", "EZ 500", "RIP KOBE","Yesssssss", "sirrrr", "help" ,
        "Lets go", "Let’s get this bread", 
         "I love delta sig","ΔΣΦ",  "Delta sig for life", "We got this", "We are trying to win", "We gotta win!", "Bread time", "Pizza time", "Pool time", "Showfety’s coins", "Lets win this ish",
         "Dub seasonnnn", "Woot Woot", "I love marvel", "Im a niner", "Niner nation", "Lol smiley face", "lets goo delta sigs", "WE gotta win this ish", "Red cups are the best", "im getting tired",
         "my fingers hurt", "My eyes are tired", "Pizzaaaa", "hot dogs", "burgers", "ramen", "FIve Guys", "I love food", "go chiefs", "super bowl 55 is coming", "jamis is lame", 
         "I love haven”, “haven4","haven haven", "I love my cat", "I kind of like dogs","“Kellan is the GOAT", 
         "Gabubu", "Dub season boys!","ΔΣΦ",  "Yes sir", "Pizza time", "America", "Ok", "Dsig", "Love it boys" ,"Get it", 
         "Lol", "Best there ever was", "Love life gentlemen", "pizza time", "Lets win it", "pizzzzzzaaaaa time",
        "Summer time tho", "Team Joe exotic", "Love life", "Lets win this", "Goodluck lol", "big win”, “oh yes",
        "Yesssssss", "sirrrr",
        "Keep", "pounding",
        "I", "like", "oranges", "Word", "I miss ricky", "Lets get these chips", 
        "Cuppa army", "Cuppa army 2.0", "Lets goo", "we got this", "Lets go.",
        "YITBOS.", "Let’s get this bread.", "Moody the goat.", "I love delta sig.", 
        "Delta sig for life.", "ΔΣΦ", "We got this.", "We are trying to win.", "We gotta win!.,"
        "Bread time.", "Pizza time.", "Pool time.", "Showfety’s coins.", "Lets win this ish.", 
        "Dub seasonnnn.", "Woot Woot.", "I love marvel.", "Im a niner.", "Niner nation.", "Lol smiley face.", 
        "lets goo delta sigs.", "WE gotta win this ish.","ΔΣΦ",  "Red cups are the best.", "im getting tired.",
        "oh yes.","YITBOS", "EZ DUB", "=)", "EZ 500", "RIP KOBE","Yesssssss", "sirrrr", "help" ,
        "Lets go", "Let’s get this bread", 
         "I love delta sig", "Delta sig for life", "We got this", "We are trying to win", "We gotta win!", "Bread time", "Pizza time", "Pool time", "Showfety’s coins", "Lets win this ish",
         "Dub seasonnnn", "Woot Woot", "I love marvel", "Im a niner", "Niner nation", "Lol smiley face", "lets goo delta sigs", "WE gotta win this ish", "Red cups are the best", "im getting tired",
         "my fingers hurt", "My eyes are tired", "Pizzaaaa", "hot dogs", "burgers", "ramen", "FIve Guys", "I love food", "go chiefs", "super bowl 55 is coming", "jamis is lame", 
         "I love haven”, “haven4","haven haven", "I love my cat", "I kind of like dogs","“Kellan is the GOAT", 
         "Gabubu", "Dub season boys!", "Yes sir", "Pizza time", "America", "Ok", "Dsig", "Love it boys" ,"Get it", 
         "Lol", "Best there ever was", "Love life gentlemen", "pizza time", "Lets win it", "pizzzzzzaaaaa time",
        "Summer time tho", "ΔΣΦ", "Team Joe exotic", "Love life", "Lets win this", "Goodluck lol", "big win”, “oh yes",
        "Yesssssss", "sirrrr",
        "Keep", "pounding",
        "I", "like", "oranges", "Word", "I miss ricky", "Lets get these chips", "ΔΣΦ", 
        "Cuppa army", "Cuppa army 2.0", "Lets goo", "we got this", "Lets go.",
        "YITBOS.", "Let’s get this bread.", "Moody the goat.", "I love delta sig.", 
        "Delta sig for life.", "We got this.", "We are trying to win.", "We gotta win!.,"
        "Bread time.", "Pizza time.", "Pool time.", "Showfety’s coins.", "Lets win this ish.", 
        "Dub seasonnnn.", "Woot Woot.", "I love marvel.", "Im a niner.", "Niner nation.", "Lol smiley face.", 
        "lets goo delta sigs.", "WE gotta win this ish.", "Red cups are the best.", "im getting tired.",
        "oh yes.","YITBOS", "EZ DUB", "=)", "EZ 500", "RIP KOBE","Yesssssss", "sirrrr", "help" ,
        "Lets go", "Let’s get this bread", 
         "I love delta sig", "Delta sig for life", "We got this", "We are trying to win", "We gotta win!", "Bread time", "Pizza time", "Pool time", "Showfety’s coins", "Lets win this ish",
         "Dub seasonnnn", "Woot Woot", "I love marvel", "Im a niner", "Niner nation", "Lol smiley face", "lets goo delta sigs", "WE gotta win this ish", "Red cups are the best", "im getting tired",
         "my fingers hurt", "My eyes are tired", "Pizzaaaa", "hot dogs", "burgers", "ramen", "FIve Guys", "I love food", "go chiefs", "super bowl 55 is coming", "jamis is lame", 
         "I love haven”, “haven4","haven haven", "I love my cat", "I kind of like dogs","“Kellan is the GOAT", 
         "Gabubu", "Dub season boys!", "Yes sir", "Pizza time", "America", "Ok", "Dsig", "Love it boys" ,"Get it", 
         "Lol", "Best there ever was", "Love life gentlemen", "pizza time", "Lets win it", "pizzzzzzaaaaa time",
        "Summer time tho", "Team Joe exotic", "Love life", "Lets win this", "Goodluck lol", "big win”, “oh yes",
        "Yesssssss", "sirrrr",
        "Keep", "pounding",
        "I", "like", "oranges", "Word", "I miss ricky", "Lets get these chips", 
        "Cuppa army", "Cuppa army 2.0", "Lets goo", "we got this", "Lets go.",
        "YITBOS.", "Let’s get this bread.", "Moody the goat.", "I love delta sig.", 
        "Delta sig for life.", "We got this.", "We are trying to win.", "We gotta win!.,"
        "Bread time.", "Pizza time.", "Pool time.", "Showfety’s coins.", "Lets win this ish.", 
        "Dub seasonnnn.", "Woot Woot.", "I love marvel.", "Im a niner.", "Niner nation.", "Lol smiley face.", 
        "lets goo delta sigs.", "WE gotta win this ish.", "Red cups are the best.", "im getting tired.",
        "oh yes."]


for z in range (100000):
    p.moveTo(1120,736, 1)
    p.leftClick(1120,736, 13)
    p.typewrite(list[i])
    i+=1
    print(i)
    y = random.randint(5, 18)
    time.sleep(y)
    p.moveTo(1387,731,2)
    p.leftClick(1387, 731,9)
 #   p.scroll(100,100)
    p.leftClick(304,47,2)
    p.typewrite('https://www.instagram.com/p/B_fSM5EJwvK/')
    p.press('enter')